from decimal import Decimal
from typing import Generic, Iterable, Iterator, MutableMapping, TypeVar

K = TypeVar("K")
V = TypeVar("V")

class SortedDict(MutableMapping[K, V], Generic[K, V]):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def clear(self) -> None: ...
    def peekitem(self, index: int = ...) -> tuple[K, V]: ...
